name: Pull Request Linter

on:
  pull_request:

jobs:
  run-linting:
    name: Run Linter
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Lint Codebase
        uses: github/super-linter/slim@v4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEFAULT_BRANCH: master
          VALIDATE_ALL_CODEBASE: false
          VALIDATE_GITHUB_ACTIONS: false
          VALIDATE_JSCPD: false
          VALIDATE_JAVASCRIPT_STANDARD: false
          VALIDATE_JAVASCRIPT_ES: false
          VALIDATE_MARKDOWN: false
          VALIDATE_PYTHON_FLAKE8: false
          VALIDATE_NATURAL_LANGUAGE: false
          VALIDATE_PYTHON_MYPY: false
          VALIDATE_PYTHON_ISORT: false
          FILTER_REGEX_EXCLUDE: (.*tests/.*|*.md|.*assets/.*)
          IGNORE_GITIGNORED_FILES: true
