name: Test IoT Edge Logger

on:
  pull_request:

jobs:
  test-package:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Action
        uses: actions/checkout@v2

      - name: Setup Python v3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Test iot-edge-logger Package
        run: |
          python3 -m pip install --upgrade pip
          python3 -m pip install pytz
          pushd "./iot-edge-logger"
          python3 -m unittest discover tests
          popd
