name: Test IoT Storage Client

on:
  pull_request:

jobs:
  test-package:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Action
        uses: actions/checkout@v2

      - name: Setup Python v3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Test iot-storage-client Package
        run: |
          python3 -m pip install --upgrade pip
          python3 -m pip install azure-storage-blob==12.13.0
          python3 -m pip install aiohttp==3.8.1
          pushd "./iot-storage-client"
          python3 -m unittest discover tests -b
          popd
