name: Test

on:
  pull_request:

env:
  PYPI_USER: "__token__"

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Parse Release Tag
        id: release-tag
        run: echo ::set-output name=TAG::${GITHUB_REF/refs\/tags\//}

      - name: Output Tag
        run: |
          echo ${{ steps.release-tag.outputs.TAG }}
